
dialogo1_00='El virus z que esta en el laboratorio exploto'
dialogo1_01='y se esparcio por todo el laboratorio'
dialogo1_10='Estas delisiosas moscas an sido contaminadas'
dialogo1_11='y por ello han crecido tanto y se volvieron agresivas'
dialogo2_00='Eso es terrible!!, emi esta aqui!, sabes si'
dialogo2_01='la Dra emilia se encuentra bien?'
dialogo3_00='no lo se, no la he visto desde la explosion.'
dialogo3_10='tendras que buscarla, pero ten cuidado y llevate esto'

dialogo4_00='Hola amigo!, que te trae por aqui?'
dialogo5_00='Estoy buscando a la Dr emili,'
dialogo5_01='la has visto?'
dialogo6_00='lo siento amigo, no la he visto'
dialogo6_01='pero tengo algo que quizas te ayude'
dialogo7_00='algo que me ayude?'
dialogo8_00='si, me encontre esta traje de mosca'
dialogo8_01='si te lo pones las moscas no seran hostiles'
dialogo8_10='pero no creas que te lo dare gratis'
dialogo8_11='Nada es gratis en la vida! recuerdalo amigo'
dialogo9_00='Entonces que es lo que quieres por el traje?'
dialogo10_00='Pues veras, llevo mucho rato partiendome el coco con'
dialogo10_01='un acertijo, si lo resuelves te dare el traje'

Acertijo='ACERTIJO'
Acertijo1_0='Si una mosca pesa 50 gramos mas la mitad de su peso'
Acertijo1_1='¿Cuánto pesa la mosca?'
acertijoCorrecto='ho claro! que listo eres amigo!'
acertijoIncorrecto0='Eso no tiene sentido, acaso eres tonto?'
acertijoIncorrecto1='siento algo de pena por la Dra emilia'

